---
author: datashaman
baseurl: ""
description: "random thoughts.<br>pithy observations.<br>some gear-grinding."
emoji_dir: images
exclude:
    - Gemfile*
    - node_modules
    - package.json
    - postcss.config.js
    - vendor
future: false
github: datashaman
liquid:
    error_mode: strict
    strict_filters: true
    strict_variables: true
markdown: kramdown
paginate: 10
plugins:
    - jekyll-default-layout
    - jekyll-gist
    - jekyll-github-metadata
    - jekyll-optional-front-matter
    - jekyll-paginate
    - jekyll-postcss
    - jekyll-relative-links
    - jekyll-titles-from-headings
    - jemoji
title: sup
twitter: data_shaman
url: https://sup.datashaman.com
