---
author: datashaman
baseurl: ""
description: "Random thoughts, observations, occasional gear-grinding."
disqus-id: datashaman
email: marlinf@datashaman.com
future: false
github: datashaman
markdown: kramdown
paginate: 5
permalink: /:year/:month/:day-:title
plugins:
    - jekyll-paginate
sass:
    style: :compressed
title: sup
twitter: data_shaman
url: https://sup.datashaman.com
