---
author: datashaman
description: "random thoughts.<br>pithy observations.<br>occasional gear-grinding."
future: false
github: datashaman
markdown: kramdown
paginate: 5
# permalink: /:year/:month/:day-:title
sass:
    style: :compressed
title: sup
twitter: data_shaman
url: https://sup.datashaman.com
