source "https://rubygems.org"

group :jekyll_plugins do
    gem 'jekyll-default-layout'
    gem 'jekyll-gist'
    gem 'jekyll-github-metadata'
    gem 'jekyll-optional-front-matter'
    gem 'jekyll-paginate'
    gem 'jekyll-relative-links'
    gem 'jekyll-titles-from-headings'
    gem 'jemoji'
end
