name: sup

on:
  push:
    branches:
      - master

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install yarn deps
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: Build yarn assets
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build

      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install jekyll & build site
        uses: limjh16/jekyll-action-ts@v2
        env:
          PAGES_REPO_NWO: datashaman/sup.datashaman.com
        with:
          enable_cache: true
          format_output: true

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
