name: sup

on:
  push:
    branches:
      - gh-pages

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: install yarn deps
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: build yarn deps
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build

      - name: install jekyll & build site
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true
          format_output: true

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/_site
